-- Align production databases that were previously updated outside Prisma migrations.
-- All statements are idempotent so deploy remains safe for Neon and existing data.

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "username" TEXT;
UPDATE "User"
SET "username" = COALESCE(NULLIF("username", ''), NULLIF("email", ''), "id")
WHERE "username" IS NULL OR "username" = '';
ALTER TABLE "User" ALTER COLUMN "username" SET NOT NULL;
ALTER TABLE "User" ALTER COLUMN "email" DROP NOT NULL;
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'cashier';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS "User_username_key" ON "User"("username");

ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "quantity" INTEGER NOT NULL DEFAULT 0;
UPDATE "Product" SET "quantity" = COALESCE("quantity", "stock", 0);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "costPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sellPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
UPDATE "Product" SET "sellPrice" = COALESCE("sellPrice", "price", 0);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "supplier" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "returnDays" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "debtAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "supplierPhone" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "date" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
CREATE INDEX IF NOT EXISTS "Product_isDeleted_idx" ON "Product"("isDeleted");

ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "dateISO" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "date" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "time" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "returnedTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'Sale' AND column_name = 'paymentType'
  ) THEN
    UPDATE "Sale"
    SET "paymentMethod" = COALESCE("paymentMethod", "paymentType", 'cash');
  ELSE
    UPDATE "Sale"
    SET "paymentMethod" = COALESCE("paymentMethod", 'cash');
  END IF;
END $$;
UPDATE "Sale"
SET
  "dateISO" = COALESCE("dateISO", TO_CHAR("createdAt", 'YYYY-MM-DD')),
  "date" = COALESCE("date", TO_CHAR("createdAt", 'DD.MM.YYYY')),
  "time" = COALESCE("time", TO_CHAR("createdAt", 'HH24:MI'));
ALTER TABLE "Sale" ALTER COLUMN "dateISO" SET NOT NULL;
ALTER TABLE "Sale" ALTER COLUMN "date" SET NOT NULL;
ALTER TABLE "Sale" ALTER COLUMN "time" SET NOT NULL;
ALTER TABLE "Sale" ALTER COLUMN "paymentMethod" SET NOT NULL;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'active';
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "sellerId" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "sellerName" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "sellerRole" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS "Sale_status_dateISO_idx" ON "Sale"("status", "dateISO");
CREATE INDEX IF NOT EXISTS "Sale_sellerId_idx" ON "Sale"("sellerId");

ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT 'Mahsulot';
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "sku" TEXT;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "costPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "returnedQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "returnStatus" TEXT NOT NULL DEFAULT 'none';

CREATE TABLE IF NOT EXISTS "SalesDay" (
  "id" TEXT NOT NULL,
  "dateISO" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "cash" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "card" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "transfer" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "returnedTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "count" INTEGER NOT NULL DEFAULT 0,
  "closedBy" TEXT,
  "autoClosed" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SalesDay_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "SalesDay_dateISO_key" ON "SalesDay"("dateISO");
CREATE INDEX IF NOT EXISTS "SalesDay_dateISO_idx" ON "SalesDay"("dateISO");

CREATE TABLE IF NOT EXISTS "Return" (
  "id" TEXT NOT NULL,
  "saleId" TEXT NOT NULL,
  "saleItemId" TEXT,
  "productId" TEXT,
  "productName" TEXT NOT NULL,
  "sku" TEXT,
  "quantity" INTEGER NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "reason" TEXT NOT NULL,
  "paymentMethod" TEXT,
  "sellerId" TEXT,
  "sellerName" TEXT,
  "sellerRole" TEXT,
  "date" TEXT NOT NULL,
  "dateISO" TEXT NOT NULL,
  "time" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Return_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "Return_dateISO_idx" ON "Return"("dateISO");
CREATE INDEX IF NOT EXISTS "Return_saleId_idx" ON "Return"("saleId");

ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "debt" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "paid" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "deadline" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS "SupplierTransaction" (
  "id" TEXT NOT NULL,
  "supplierId" TEXT NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'inventory',
  "status" TEXT,
  "productName" TEXT,
  "amount" DOUBLE PRECISION NOT NULL,
  "phone" TEXT,
  "date" TEXT NOT NULL,
  "time" TEXT NOT NULL,
  "note" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SupplierTransaction_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "SupplierTransaction_supplierId_createdAt_idx" ON "SupplierTransaction"("supplierId", "createdAt");

CREATE TABLE IF NOT EXISTS "Expense" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "category" TEXT NOT NULL DEFAULT 'Boshqa',
  "amount" DOUBLE PRECISION NOT NULL,
  "note" TEXT,
  "date" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Shift" (
  "id" TEXT NOT NULL,
  "cashierName" TEXT NOT NULL,
  "openedById" TEXT,
  "openedByName" TEXT,
  "closedById" TEXT,
  "closedByName" TEXT,
  "openingCash" DOUBLE PRECISION NOT NULL,
  "closingCash" DOUBLE PRECISION,
  "cashDifference" DOUBLE PRECISION,
  "totalSales" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "cashSales" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "cardSales" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "transferSales" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "transactions" INTEGER NOT NULL DEFAULT 0,
  "openedAt" TEXT NOT NULL,
  "openedAtISO" TIMESTAMP(3) NOT NULL,
  "closedAt" TEXT,
  "closedAtISO" TIMESTAMP(3),
  "duration" TEXT,
  "date" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'open',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Shift_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "Shift_status_idx" ON "Shift"("status");
CREATE INDEX IF NOT EXISTS "Shift_closedAtISO_idx" ON "Shift"("closedAtISO");

CREATE TABLE IF NOT EXISTS "ActivityLog" (
  "id" TEXT NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'general',
  "title" TEXT NOT NULL,
  "description" TEXT,
  "userId" TEXT,
  "userName" TEXT NOT NULL,
  "userRole" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "time" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ActivityLog_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "ActivityLog_createdAt_idx" ON "ActivityLog"("createdAt");

CREATE TABLE IF NOT EXISTS "TelegramSettings" (
  "id" TEXT NOT NULL DEFAULT 'singleton',
  "botToken" TEXT,
  "chatId" TEXT,
  "newSale" BOOLEAN NOT NULL DEFAULT true,
  "dailyReport" BOOLEAN NOT NULL DEFAULT true,
  "returns" BOOLEAN NOT NULL DEFAULT true,
  "lowStock" BOOLEAN NOT NULL DEFAULT true,
  "outOfStock" BOOLEAN NOT NULL DEFAULT true,
  "shiftOpen" BOOLEAN NOT NULL DEFAULT true,
  "shiftClose" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TelegramSettings_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "dateISO" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "total" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "cash" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "card" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "transfer" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "returnedTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "closedBy" TEXT;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "autoClosed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "SalesDay" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "saleId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "saleItemId" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "productId" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "productName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "sku" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "quantity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "reason" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "sellerId" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "sellerName" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "sellerRole" TEXT;
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "dateISO" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "time" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "supplierId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'inventory';
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "productName" TEXT;
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "time" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "note" TEXT;
ALTER TABLE "SupplierTransaction" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'Boshqa';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "note" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "cashierName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "openedById" TEXT;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "openedByName" TEXT;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "closedById" TEXT;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "closedByName" TEXT;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "openingCash" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "closingCash" DOUBLE PRECISION;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "cashDifference" DOUBLE PRECISION;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "totalSales" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "cashSales" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "cardSales" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "transferSales" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "transactions" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "openedAt" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "openedAtISO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "closedAt" TEXT;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "closedAtISO" TIMESTAMP(3);
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "duration" TEXT;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'open';
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Shift" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'general';
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "userName" TEXT NOT NULL DEFAULT 'Noma''lum foydalanuvchi';
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "userRole" TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "time" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "botToken" TEXT;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "chatId" TEXT;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "newSale" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "dailyReport" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "returns" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "lowStock" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "outOfStock" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "shiftOpen" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "shiftClose" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "TelegramSettings" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Sale_sellerId_fkey') THEN
    ALTER TABLE "Sale" ADD CONSTRAINT "Sale_sellerId_fkey"
    FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Return_saleId_fkey') THEN
    ALTER TABLE "Return" ADD CONSTRAINT "Return_saleId_fkey"
    FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Return_saleItemId_fkey') THEN
    ALTER TABLE "Return" ADD CONSTRAINT "Return_saleItemId_fkey"
    FOREIGN KEY ("saleItemId") REFERENCES "SaleItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Return_productId_fkey') THEN
    ALTER TABLE "Return" ADD CONSTRAINT "Return_productId_fkey"
    FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Return_sellerId_fkey') THEN
    ALTER TABLE "Return" ADD CONSTRAINT "Return_sellerId_fkey"
    FOREIGN KEY ("sellerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'SupplierTransaction_supplierId_fkey') THEN
    ALTER TABLE "SupplierTransaction" ADD CONSTRAINT "SupplierTransaction_supplierId_fkey"
    FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Shift_openedById_fkey') THEN
    ALTER TABLE "Shift" ADD CONSTRAINT "Shift_openedById_fkey"
    FOREIGN KEY ("openedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Shift_closedById_fkey') THEN
    ALTER TABLE "Shift" ADD CONSTRAINT "Shift_closedById_fkey"
    FOREIGN KEY ("closedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ActivityLog_userId_fkey') THEN
    ALTER TABLE "ActivityLog" ADD CONSTRAINT "ActivityLog_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
